server:
  port: 80

spring:
  application:
    name: cloud-alibaba-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  cloud-nacos-provider: http://cloud-alibaba-provider