server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # register in eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true


#setup OpenFeign client timeout (OpenFeign support ribbon by default)
ribbon:
  #connect time out
  ReadTimeout: 5000
  #read source time out
  ConnectTimeout: 5000

logging:
  level:
    # feign logging level debug
    com.vilin.springcloud.service.PaymentFeignService: Debug


CLOUD-PAYMENT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule