server:
  port: 5002

spring:
  application:
    name: cloud-config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: config-client5002
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"