server:
  port: 9002

spring:
  application:
    name: cloud-hystrix-turbine

turbine:
  appConfig: CLOUD-ORDER-HYSTRIX-SERVICE,CLOUD-PAYMENT-HYSTRIX-SERVICE
  clusterNameExpression: new String("default")
  combine-host-port: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: turbine9002
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: turbine.stream

